name: Check Version and Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Check Version and Tag Action
        uses: aktin/aktin-github-actions/python-version-tagging@main
        with:
          file-path: '/src/sftp_export.py'
